import { Box, box } from './box/box';
import optional from './optional/helper';
import { Some, some } from './optional/some';
import { None, none } from './optional/none';
import { Lazy, lazy } from './lazy/lazy';
import { Task, task } from './task/task';
import { Success, success } from './result/success';
import { Failure, failure } from './result/failure';
import { nth, randomIndex, randomElement } from './array/array';
import identity from './identity/identity';
export { Box, box };
export { optional };
export { Some, some };
export { None, none };
export { Lazy, lazy };
export { Task, task };
export { Success, success };
export { Failure, failure };
export { identity };
export { nth, randomIndex, randomElement };
